### ISSUE TITLE
Styling of popovers breaks with latest antd version

### ISSUE THREAD

**Issue by jpreis** [xrutayisire/react-js-cron#1]
**Describe the bug**
When using react-js-cron in conjunction with the latest version of antd (4.6.3 as of writing this), the styling of popovers is broken (the entries aren't shown in a grid). The `package.json` only specifices `>=4.1.0` as the version for this peer dependency. This problem doesn't arise when using antd 4.2.5.

**To Reproduce**
Codesandbox: https://codesandbox.io/s/reat-js-cron-5chdk

Click on any dropdown

**Expected behavior**
Items in the popover should be displayed in a grid.

**Screenshots**
With antd 4.6.3:
<img width="1652" alt="latest" src="https://user-images.githubusercontent.com/1215057/92730935-bf550f00-f374-11ea-9b4e-b50c84ad523f.png">

With antd 4.2.5:
<img width="1654" alt="4_2_5" src="https://user-images.githubusercontent.com/1215057/92730992-ced45800-f374-11ea-9ee7-d4710ffa6099.png">

**Additional context**
The layout breaks since there is an extraneous `div` inside the grid container instead of the grid-items. Somehow the way the items are rendered within the popover has changed between these two versions (seeing the additional `rc-virtual-list` classes that are present when using 4.6.3).

**Comment by xrutayisire** [comment]
Hi,

Thanks for the report 👍 
I will investigate the problem and try to make a fix.

**Comment by xrutayisire** [comment]
This issue has been fixed with react-js-cron version 1.1.0. 

Thanks a lot for finding this bug and let me know if there is something else that cause a problem now. 

Be sure to read the changelog before using new version 😉
