### ISSUE TITLE
Pressing clear inside 'Select' does not show desired result.

### ISSUE THREAD

**Issue by ashishRudder** [xrutayisire/react-js-cron#18]
**Describe the bug**
When clicked on `clear` button in `minutes` or `hours` Select, the value inside don't get cleared.

**To Reproduce**
1. Go to 'Cron widget'
2. Click on 'minutes dropdown'
3. Add at least 5 items.
4. Close the dropdown
5. Click on `clear/X` button on the right.
6. See bug where the values don't get clear.

**Expected behavior**
Once clicked on clear, the values should get removed.

**CodeSandbox**
https://codesandbox.io/s/cron-antd-rcjv9

**Versions (please complete the following information):**
 - react-js-cron version 1.3.0
 - Ant Design version: 4.18.6
 - React version: 17.0.2
 - OS: macOS
 - Browser Firefox

**Additional context**
The issue is not present when switching to antd version 4.17.2

Demo:
https://user-images.githubusercontent.com/74043614/153365290-5a82cb1a-d727-476c-8a9d-ded9a547e238.mov

**Comment by xrutayisire** [comment]
There is an open issue on antd side. I will wait to see if they can revert this new behavior (bug for me) or not.  

cf: https://github.com/ant-design/ant-design/issues/33790

**Comment by xrutayisire** [comment]
It's closed on antd side, so now you should not have the bug anymore: https://github.com/ant-design/ant-design/issues/33790
