### ISSUE TITLE
Single option select feature in the drowdown

### ISSUE THREAD

**Issue by alok01rai** [xrutayisire/react-js-cron#22]
There is no option to restrict visitors to select only one value from the dropdown,  i. e.  If I would like to restrict visitors to select only one month, only one hour,  day or minute I can't restrict.  

It will be great if you can add a prop saying mode Single.

**Comment by xrutayisire** [comment]
Hello again,

Thanks for the feature request following our [discussion](https://github.com/xrutayisire/react-js-cron/discussions/21).

I added a new optional prop "mode", by default is "multiple" but can be set to "single". 

You can see the type definition [here](https://github.com/xrutayisire/react-js-cron/blob/ab287ff5622681f96ba1f205f5310c3eec90117a/src/types.ts#L130).

And the demo here: https://xrutayisire.github.io/react-js-cron/?path=/docs/reactjs-cron--single-selection-mode

Can you confirm that it's what you want before I release the changes ? 😃

**Comment by alok01rai** [comment]
It's perfect. Please release the changes.
Thanks for your speedy support.

**Comment by xrutayisire** [comment]
Thanks for the feedback!

New release [v1.4.0](https://www.npmjs.com/package/react-js-cron/v/1.4.0) is out in the wild with the new prop "mode" 🎉

Let me know if there is a problem with the release.

**Comment by alok01rai** [comment]
Hi @xrutayisire ,

Can we enable periodicityOnDoubleClick in single mode?

Also while selecting Month or Year is there option to remove and criteria. I,e, When you select Month there we can select the date as well as Day, so is there any option to remove day option from there?

**Comment by alok01rai** [comment]
periodicityOnDoubleClick in single mode  - Purpose If I would like to run cron on every 15 mins.

**Comment by vivek-kandhvar** [comment]
Thanks for adding the support for single selection. If we enable single mode selection, the dropdown should auto close on selecting a value. Right now it always stays until the customer clicks outside.

**Comment by xrutayisire** [comment]
Hello :)

I agree that I could be improved. I don't have the time to do it right now (holidays).

I will handle this issue and your comment when I come back.

**Comment by xrutayisire** [comment]
Hello,

New release [v2.0.0](https://github.com/xrutayisire/react-js-cron/releases/tag/v2.0.0) 🥳

@alok01rai, periodicityOnDoubleClick is not ignored anymore when single mode is active, so you can use it.
@alok01rai, with new props allowedDropdowns and allowedPeriods, you should be able to display or hide what you want, when you want it. It's dynamic, so feel free to try it.
@vivek-kandhvar, when single mode is active AND periodicityOnDoubleClick is false the dropdown will close itself atomatically after any selection.
