### ISSUE TITLE
What is useCronReducer? How use it?

### ISSUE THREAD

**Issue by TierC24** [xrutayisire/react-js-cron#26]
import { useState } from "react";
import { Divider, Input as AntdInput } from "antd";
import Cron, { CronError, CronProps } from "react-js-cron";
import "antd/dist/antd.css";
import { InfoCircleOutlined } from '@ant-design/icons';
import useCronReducer from 'react-js-cron';

export default function Demo() {

  
  const defaultValue = '30 5 * * 1,6'

  /**
   * old use 
   * const defaultValue = '30 5 * * 1,6'
   * const [values, dispatchValues] = useCronReducer(props)    => error
   *  const [error, onError] = useState<CronError>()
   */

  let props : CronProps = {
    value:defaultValue,
    setValue:(defaultValue:string)=>{}
  }

  const [values, dispatchValues] = useCronReducer(props)  //=>error 
  const [error, onError] = useState<CronError>()

  return (
    <div>
      <AntdInput
        value={values.inputValue}
        onChange={(event) => {
          dispatchValues({
            type: 'set_input_value',
            value: event.target.value,
          })
        }}
        onBlur={() => {
          dispatchValues({
            type: 'set_cron_value',
            value: values.inputValue,
          })
        }}
        onPressEnter={() => {
          dispatchValues({
            type: 'set_cron_value',
            value: values.inputValue,
          })
        }}
      />

      <Divider>OR</Divider>

      <Cron
        value={values.cronValue}
        setValue={(newValue: string) => {
          dispatchValues({
            type: 'set_values',
            value: newValue,
          })
        }}
        onError={onError}
      />

      <div>
        <InfoCircleOutlined style={{ marginRight: 5 }} />
        <span style={{ fontSize: 12 }}>
          Double click on a dropdown option to automatically select / unselect a
          periodicity
        </span>
      </div>

      <p style={{ marginTop: 20 }}>
        Error: {error ? error.description : 'undefined'}
      </p>
    </div>
  )
}

**Comment by TierC24** [comment]
demo  https://github.com/TierC24/cron-js-bug

**Comment by xrutayisire** [comment]
Hello,

Thanks for using this package ! 😄 

Explanation here: https://github.com/xrutayisire/react-js-cron/discussions/24#discussioncomment-2588539

Xavier

**Comment by TierC24** [comment]
Thanks ,  already solve the problem!



***@***.***
 
From: Xavier Rutayisire
Date: 2022-05-13 17:09
To: xrutayisire/react-js-cron
CC: TierC24; Author
Subject: Re: [xrutayisire/react-js-cron] What is useCronReducer? How use it? (Issue #26)
Hello,
Thanks for using this package ! ????
Explanation here: #24 (reply in thread)
Xavier
