### ISSUE TITLE
Single selection for when Month or Year is active.

### ISSUE THREAD

**Issue by radesai21** [xrutayisire/react-js-cron#28]
**Is your feature request related to a problem? Please describe.**
It would be great to have the ability to restrict the cron schedule to only happen once when `Every Month` or `Every Year` is active. Currently when month or year is selected the schedule contains an `AND <Day of the Week>`. See screenshot of example page below.

**Describe the solution you'd like**
Ideally if its possible a new config or using the same `mode='single'` to hide that dropdown when month or year is selected.

My goal is to be able to read the following:
'Every `month` on `4` at `3`:`30`'
'Every `year` in `APR` on `4` at `3`:`30`'

**Describe alternatives you've considered**
I have tried to hide the dropdown using CSS through the `className` prop & overriding the schedule value in the `setValue` callback. I ran into issues with that route because when you flip from week to month or week to year the schedule is not changed. The value remains the same making it hard to know wether month or year is currently selected

**Additional context**
![image](https://user-images.githubusercontent.com/95231401/175111082-3169177a-e79b-4482-9c14-aebcb9e56d29.png)

![feature-request](https://user-images.githubusercontent.com/95231401/175115131-1999668f-b4bb-40df-8f6a-bf276c532901.gif)

**Comment by xrutayisire** [comment]
Hello,

First thank for using this package and for this well described issue!

I just a release the new [v2.0.0](https://github.com/xrutayisire/react-js-cron/releases/tag/v2.0.0) containing a new feature for you 🥳

2 new props: allowedDropdowns and allowedPeriods.

Now you should be able to hide the week-days dropdown for example as in your example:

<img width="521" alt="Screenshot 2022-06-26 at 01 35 38" src="https://user-images.githubusercontent.com/19946868/175795794-f6cb1f2e-bd84-4fb8-90d7-6eff9c541198.png">
<img width="583" alt="Screenshot 2022-06-26 at 01 36 07" src="https://user-images.githubusercontent.com/19946868/175795796-f476f25c-bbd9-4824-bcaf-2576dc3ce553.png">

**Comment by radesai21** [comment]
This is nice to have! However it seems to only address half of the issue. While the dropdowns are not visible with the new props, the schedule still occurs twice when monthly or yearly is selected even though the dropdowns display:

'Every `month` on `4` at `6`:`00`'
The schedule is actually set on: `0 6 4 * 0` (At 06:00 on day-of-month 4 AND on Sunday)

'Every `year` in `APR` on `4` at `6`:`0`'
The schedule is actually set on: `0 6 4 4 0` (At 06:00 on day-of-month 4 AND on Sunday in April.)

The problem is that it still uses that `AND <Day of the Week>` condition in the schedule when though its not displayed in the dropdowns.

Please take a look at the screenshot below using the example page for dynamic settings.

There is also another issue that should be addressed when `allowedDropdowns` is `['period', 'month', 'month-days', 'hours']` and `allowedPeriods` is `['year', 'month', 'week']`. When `week` is selected, the `week-days` dropdown should be displayed so a user can still select which day of the week to set the schedule to. Not just the time on Sunday. 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/95231401/175946494-b33a7547-2379-4b39-ac4b-fde7abe4fd3a.png">

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/95231401/175944309-5ec5c73f-92c5-4cfc-91e3-1b4c5f84bf07.png">

**Comment by xrutayisire** [comment]
Hum, I don’t really understand the issue, how did you put the 0 for Sunday? The goal of the feature is to not let the user select the week day, so user should not be able to select Sunday at all. If there is another way to set 0 I think it’s outside of the component scope. 
With the new feature you let the user change anything but the week days. 

For your second point, the component don’t handle the logic between the two props. If you decide to remove the week days dropdown it will not be displayed. Even if week is selected. The component don’t know the logic you want to apply. 

Maybe it could be a new feature that allow you to know which period is selected and so dev can apply some logic for the allowedDropdowns props depending on the period?

**Comment by radesai21** [comment]
I did not change the cron value, I believe the issue comes from switching from `week` to `month` or `week` to `year`. Here is a gif of how I ended up in that state for the component: (I first started with the component resetted)
![bug](https://user-images.githubusercontent.com/95231401/175953271-19debac2-8ab7-4160-bd94-e7665c557658.gif)

For the second point, it would be awesome to know which period is selected. That's the main issue I'm running into in my use case for this component. There isn't an easy way to tell which dropdown is selected where I can apply my specific logic to the allowedDropdowns prop. I am currently using plain JS to select the dropdown from the DOM & checking its value. So if there is a feature you might be able to add where we know the period that is selected then it would make it much easier!

**Comment by xrutayisire** [comment]
Oh ! I understand why you have this 0 for Sunday, it’s because you set @weekly for default value. Because of this, weekly set 0 for Sunday and it’s normal it’s the proper way to handle the shortcut weekly. (https://gist.github.com/jpluimers/6510369)
Can you set something else in your app instead of weekly?

I will think a bit more about this new feature but it could be on the setValue prop, a new param « selectedPeriod » after the first param for the new value. What do you think about this?

**Comment by radesai21** [comment]
An extra parameter on the setValue prop would be very helpful!
