### ISSUE TITLE
Invalid expression expand

### ISSUE THREAD

**Issue by engFelipeMonteiro** [xrutayisire/react-js-cron#30]
**Describe the bug**
The expand of this library is not getting a correct awnser.

**To Reproduce**
1.
On [playground](https://xrutayisire.github.io/react-js-cron/?path=/story/reactjs-cron--shortcuts) when you put "* 2-10,19-23/2 * * *" , this should be equal to [2,3,4,5,6,7,8,9,10,19,21] but it appers as "* 2-23/2 * * *".
2. The playground dont accept the following valid expression "* 2-6/2,19-23/2" ( every 2 hours off work hours)

**Comment by xrutayisire** [comment]
Hello,

Thanks for the issue!

I will check how this error happen, and I will try to fix it 👍

**Comment by xrutayisire** [comment]
v2.1.1 is released with the fix! 🎉

Your use cases should work now 💯
You can reopen this issue if you still have a problem.

Have a good day!
