### ISSUE TITLE
Unconventional cron not throwing error but changes cron value to closest accepted value

### ISSUE THREAD

**Issue by jianminggit** [xrutayisire/react-js-cron#31]
**Describe the bug**
Unconventional cron pasted in a text field does not throw an error but forcibly changing the select dropdown to its closest accepted value.

**To Reproduce**
1. Go to 'https://xrutayisire.github.io/react-js-cron/?path=/docs/reactjs-cron--track-error'
2. Type   * * * * Sun#3   in the text input 
3. Select input resets the cron value to the closest accepted value
4. No error shown

**Expected behavior**
An error should be thrown

**Comment by xrutayisire** [comment]
Thanks for the issue, good catch :)

I will try to find time during the weekend to fix this bug.

**Comment by xrutayisire** [comment]
v2.1.2 is released with the fix! 🎉

It will throw an error now if any value is not correct!
You can reopen this issue if you still found some Cron that should throw an error but don't 🙂 

Have a good day!
