### ISSUE TITLE
Custom style feature

### ISSUE THREAD

**Issue by alanskovrlj** [xrutayisire/react-js-cron#32]
Please add abbility to add custom styles to the button and select options through props.

**Comment by xrutayisire** [comment]
Hello,

Please respect the issue template, here I don't know what you want. So what I can answer is, it's already possible to add custom style thanks to available className.

In the following example you can use:
- .my-project-cron-clear-button
- .my-project-cron-select

https://xrutayisire.github.io/react-js-cron/?path=/story/reactjs-cron--custom-style
