### ISSUE TITLE
Where is convertor export?

### ISSUE THREAD

**Issue by reikrom** [xrutayisire/react-js-cron#47]
Is there not supposed to be a convertor export?

**Comment by xrutayisire** [comment]
Hello,

You're right. I'm going to publish a new version today, so you can use it with the new version!

Sorry for the delay

**Comment by reikrom** [comment]
Thanks, I thought i was losing my mind. Can't wait to drop `cronstrue` undeeded 1mb package.

**Comment by xrutayisire** [comment]
So sorry for the delay 😞 

But the new release is live v3.1.0!
