### ISSUE TITLE
Cron has broken style in antd 5

### ISSUE THREAD

**Issue by kloon15** [xrutayisire/react-js-cron#54]
**Describe the bug**
Cron component has broken style when used in antd 5. Hour and minute picker is unusable.

**CodeSandbox**
[A CodeSandbox link with the bug.](https://codesandbox.io/s/withered-sunset-xy9sn7)

**Versions (please complete the following information):**
 - react-js-cron version [3.1.0]
 - Ant Design version: [5.3.2]
 - React version: [18.2.0]
 - OS: [Windows]
 - Browser [Firefox]

**Comment by xrutayisire** [comment]
Hello,

As mentioned in the README, since v3.0 you need to manually import Cron styles:

```ts
import 'react-js-cron/dist/styles.css'
```

**CodeSandbox**:
https://codesandbox.io/s/sharp-edison-7cph0n?file=/src/App.tsx

**Comment by kloon15** [comment]
Thank you, i missed it since i went straight to the demo and usage which is at top of the page.
