### ISSUE TITLE
[antd: Select] `showArrow` is deprecated

### ISSUE THREAD

**Issue by vugardadalov** [xrutayisire/react-js-cron#60]
**Describe the bug**
In the latest antd version `showArrow` prop of Select component is deprecated.

**To Reproduce**

```tsx
import { Cron } from 'react-js-cron';

import 'react-js-cron/dist/styles.css';

function Cronn() {
  const setValue = (val) => {
    console.log('Cron val', val);
  };
  return <Cron value="0 0 * * THU" setValue={setValue} />;
}

export default Cronn;
```

**Screenshots**
![image](https://github.com/xrutayisire/react-js-cron/assets/18144465/5d774532-c6e3-4082-8cdc-a51c25eadecf)

**CodeSandbox**
[A CodeSandbox link with the bug.](https://stackblitz.com/edit/react-ltinjk?file=demo.tsx)

**Versions (please complete the following information):**
 - react-js-cron version [^4.1.0]
 - Ant Design version: [^5.9.0]
 - React version: [^18.2.0]
 - Browser [chrome]

**Comment by nurlanmamedov** [comment]
I got same issue.

**Comment by vugardadalov** [comment]
Thanks for attention. Waiting for... ))

**Comment by xrutayisire** [comment]
Doing that today yes 😉

**Comment by xrutayisire** [comment]
v5.0.0 released with the fix 🚀
