### ISSUE TITLE
Select field values going blank.

### ISSUE THREAD

**Issue by robincsamuel** [xrutayisire/react-js-cron#9]
**Describe the bug**

Select values blank.

**Screenshots**

<img width="621" alt="Screenshot 2021-06-12 at 1 06 11 AM" src="https://user-images.githubusercontent.com/4545992/121740373-a0112b00-cb1a-11eb-816e-ed99c3b941c5.png">

<img width="703" alt="Screenshot 2021-06-12 at 1 07 05 AM" src="https://user-images.githubusercontent.com/4545992/121740381-a30c1b80-cb1a-11eb-8812-e970ecd281f9.png">
<img width="664" alt="Screenshot 2021-06-12 at 1 07 12 AM" src="https://user-images.githubusercontent.com/4545992/121740386-a3a4b200-cb1a-11eb-811b-4c531e836273.png">

**Desktop (please complete the following information):**
 - OS: OSX 11.4
 - Browser : Brave (Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64))

**Additional context**

Looks like the `z-index: -1` added in f1c6ad59aa8969df6054da10c213cec585bcc789 is causing the issue. Please see the screenshot, works fine if I uncheck z-index.

**Comment by xrutayisire** [comment]
Hi, 

Thanks for the issue. Which version of antd do you have ?

Also, can you give me a CodeSanbox with the bug please

**Comment by robincsamuel** [comment]
Sure, I'll do it in some time. Just realized the problem is only when the component is in a modal.  I also had a problem with displaying the select options due to the z-index.

 I added the following CSS to solve that issue.

```
cron-select-dropdown {
  z-index: 1300
}
```

**Comment by robincsamuel** [comment]
@xrutayisire Sorry, I couldn't reproduce it. I'm using a custom theme so I guess some CSS related to that is causing the issue. In further debugging, I see it happens only if the parent div has a scroll.
